global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'host1'
    static_configs:
      - targets: ['192.168.64.13:9100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
